### ISSUE TITLE
background Image doesnt work

### ISSUE THREAD

**Issue by afew-max** [lewisdoesstuff/bento-next#10]
Put jpg in images folder, background image doesnt change. Also URL to image doesnt work. 
The complete path to the image also doesnt work. ` ./src/assets/images/background.jpg`

Im using the page in a docker container. 

`// Place a background image in ./src/assets/images/ and provide the file name.
  // Alternatively, provide a URL to an image. If the page is served over https, you may have issues loading images from insecure origins.
  // Set to "" to disable.
  backgroundImage: 'background.jpg',
  themes: [
    // List of installed themes, add your own themes in ./src/assets/css/themes and include it in the array below.
    'arc',
    'bento',
    'catppuccin-frappe',
    'catppuccin-macchiato',
    'catppuccin-mocha',
    'conceptdark', // dark mode only
    'monokai',
    'nord',
    'sakura',
    'solarized',
  ],`

**Comment by lewisdoesstuff** [comment]
Resolved in the latest version, should be okay to use just the file name as the `backgroundImage` value.

**Comment by afew-max** [comment]
I tested it, but the image ist still not loading. I used the same config.ts and the same image and URL as before.

**Comment by lewisdoesstuff** [comment]
Hmm, that's strange.  
Do you get any errors in the browser console when opening the page?

You may have to add another volume mount to your docker-compose, like `/path/to/background.jpg:/src/assets/images/background.jpg` for a custom image to work, but the pre-included one _should_ work okay

**Comment by afew-max** [comment]
there is no error and i tried it now with the default image but also this one doesnt get recognized 

I tried also /path/to/background.jpg:/src/assets/images/background.jpg in the compose file, but its not working

**Comment by lewisdoesstuff** [comment]
Have you grabbed the latest image version?  
`docker image pull lewisdoesstuff/bento-next`  

It should log an error if it couldn't load the image.  
If not, try passing a URL to an image hosted online to see if that works

**Comment by afew-max** [comment]
with the new image the default background is loading, I deleted the default background file of /src/assets/images and moved another file with a differente filename, then i get undefined error in the console

the starnge thing is, if i just type background.jpg as backgroundImage in the config, the default background is loading, but I delted the .jpg file and there is no file with the name background.jpg in the src folder

**Comment by lewisdoesstuff** [comment]
Thanks, can you try adding that volume mount back into your compose file?

**Comment by afew-max** [comment]
I added this to docker-compose file, but still no background and undefined in console  
- /home/username/bento-next/src/assets/images/afewbackground.jpg:/src/assets/images/afewbackground.jpg

I tried also this
- /home/username/bento-next/src/assets/images/afewbackground.jpg:/src/assets/images/background.jpg

**Comment by lewisdoesstuff** [comment]
That's so strange, i'll try it out after i finish work and see if i can get a fix

**Comment by lewisdoesstuff** [comment]
Just tested this and pushed a new default `docker-compose.yml`.  

Your bind mount needs to be:  
`./src/assets/images:/src/src/assets/images`  

The additonal `/src` is required on the container path as our workdir is `/src`.

**Comment by afew-max** [comment]
its working

Is it possible to change the icon in the taskbar? I already tried to replace the .svg file in src/assets

**Comment by lewisdoesstuff** [comment]
I _think_ you can add it to the `/public` dir asn`favicon.ico`.  

You'll need another bind mount for `./public/favicon.ico:/src/public/favicon.ico`  

I'll look to make this a bit more user-friendly at some point
